import { Classroom, Student, RoomConfig, Institution, AppUser } from '../types';

export const AVATAR_COLORS = [
  '#3b82f6', // blue
  '#10b981', // emerald
  '#8b5cf6', // purple
  '#f59e0b', // amber
  '#ec4899', // pink
  '#06b6d4', // cyan
  '#f97316', // orange
  '#14b8a6', // teal
  '#6366f1', // indigo
  '#84cc16', // lime
  '#e11d48', // rose
  '#0284c7', // sky
];

export function createDefaultRoomConfig(rows = 5, cols = 6, layoutType: RoomConfig['layoutType'] = 'rows'): RoomConfig {
  const activeDesks: Record<string, boolean> = {};
  
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const key = `r${r}_c${c}`;
      if (layoutType === 'pairs') {
        // Leave corridor between pairs: e.g. columns (0,1), corridor (empty or aisle), (2,3), etc.
        // Or if 6 columns: cols 0,1 are pair 1, col 2 is aisle? Alternatively in pairs, all active but visual grouping
        activeDesks[key] = true;
      } else if (layoutType === 'u_shape') {
        // Keep outer border active, deactivate inner center
        const isBorder = r === 0 || c === 0 || c === cols - 1;
        activeDesks[key] = isBorder;
      } else if (layoutType === 'groups_4') {
        activeDesks[key] = true;
      } else {
        activeDesks[key] = true;
      }
    }
  }

  return {
    rows,
    cols,
    layoutType,
    teacherDeskPosition: 'front_left',
    boardPosition: 'top',
    doorPosition: 'back_right',
    windowPosition: 'left',
    activeDesks,
  };
}

export const SAMPLE_STUDENTS_7B: Student[] = [
  {
    id: 'std-1',
    rollNumber: 1,
    name: 'Alice Monteiro',
    nickname: 'Alice',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'calm',
    specialNeeds: ['low_vision'],
    specialNeedsNotes: 'Usa óculos com alto grau, necessita de fileiras da frente.',
    preferredRow: 'front',
    affinities: ['std-4', 'std-12'],
    antiAffinities: ['std-18'],
    affinityDetails: [
      { targetStudentId: 'std-4', level: 'high', category: 'Amizade Produtiva / Estudos', notes: 'Excelente dupla de resolução de exercícios' },
      { targetStudentId: 'std-12', level: 'medium', category: 'Apoio Pedagógico / Monitoria' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-18', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
    ],
    notes: 'Aluna muito participativa e dedicada.'
  },
  {
    id: 'std-2',
    rollNumber: 2,
    name: 'Bernardo Silva',
    nickname: 'Bê',
    gender: 'M',
    avatarColor: '#059669',
    behavior: 'talkative',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-3', 'std-7'],
    antiAffinities: ['std-5', 'std-9', 'std-14'],
    affinityDetails: [
      { targetStudentId: 'std-3', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-7', level: 'medium', category: 'Trabalho em Equipe / Projetos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-5', level: 'critical', category: 'Conversa Excessiva / Dispersão', notes: 'Conversam ininterruptamente se juntos' },
      { targetStudentId: 'std-9', level: 'moderate', category: 'Distração Mútua / Brincadeiras' },
      { targetStudentId: 'std-14', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
    ],
    notes: 'Conversa muito se sentado ao lado de Enzo ou Felipe.'
  },
  {
    id: 'std-3',
    rollNumber: 3,
    name: 'Caio Fernandes',
    nickname: 'Caio',
    gender: 'M',
    avatarColor: '#0d9488',
    behavior: 'moderate',
    specialNeeds: [],
    preferredRow: 'any',
    affinities: ['std-2', 'std-8'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-2', level: 'medium', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-8', level: 'low', category: 'Foco Compartilhado' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-4',
    rollNumber: 4,
    name: 'Beatriz Vasconcelos',
    nickname: 'Bia',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'front',
    affinities: ['std-1', 'std-6'],
    antiAffinities: ['std-14'],
    affinityDetails: [
      { targetStudentId: 'std-1', level: 'high', category: 'Apoio Pedagógico / Monitoria' },
      { targetStudentId: 'std-6', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-14', level: 'critical', category: 'Conflito / Atrito Pessoal', notes: 'Solicitação expressa dos pais e coordenação' },
    ],
  },
  {
    id: 'std-5',
    rollNumber: 5,
    name: 'Enzo Gabriel Santos',
    nickname: 'Enzo',
    gender: 'M',
    avatarColor: '#d97706',
    behavior: 'talkative',
    specialNeeds: ['adhd_focus'],
    specialNeedsNotes: 'TDAH diagnosticado. Deve ficar na frente, longe da janela e porta.',
    preferredRow: 'front',
    affinities: ['std-11'],
    antiAffinities: ['std-2', 'std-9', 'std-14', 'std-21'],
    affinityDetails: [
      { targetStudentId: 'std-11', level: 'high', category: 'Apoio Pedagógico / Monitoria', notes: 'Guilherme ajuda a manter o foco de Enzo' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-2', level: 'critical', category: 'Conversa Excessiva / Dispersão' },
      { targetStudentId: 'std-9', level: 'critical', category: 'Distração Mútua / Brincadeiras' },
      { targetStudentId: 'std-14', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
      { targetStudentId: 'std-21', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
    ],
    notes: 'Precisa de monitoramento visual do professor.'
  },
  {
    id: 'std-6',
    rollNumber: 6,
    name: 'Clara Meirelles',
    nickname: 'Clarinha',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-4', 'std-10'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-4', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-10', level: 'medium', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-7',
    rollNumber: 7,
    name: 'Davi Lucca Ribeiro',
    nickname: 'Davi',
    gender: 'M',
    avatarColor: '#059669',
    behavior: 'moderate',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-2', 'std-15'],
    antiAffinities: ['std-18'],
    affinityDetails: [
      { targetStudentId: 'std-2', level: 'medium', category: 'Trabalho em Equipe / Projetos' },
      { targetStudentId: 'std-15', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-18', level: 'moderate', category: 'Conflito / Atrito Pessoal' },
    ],
  },
  {
    id: 'std-8',
    rollNumber: 8,
    name: 'Eduardo Costa',
    nickname: 'Dudu',
    gender: 'M',
    avatarColor: '#047857',
    behavior: 'calm',
    specialNeeds: ['tall_student'],
    specialNeedsNotes: 'Muito alto (1,85m). Sentar no fundo para não obstruir colegas.',
    preferredRow: 'back',
    affinities: ['std-3', 'std-13'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-3', level: 'medium', category: 'Foco Compartilhado' },
      { targetStudentId: 'std-13', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-9',
    rollNumber: 9,
    name: 'Felipe Albuquerque',
    nickname: 'Lipe',
    gender: 'M',
    avatarColor: '#e11d48',
    behavior: 'talkative',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-5', 'std-14'],
    antiAffinities: ['std-2', 'std-17', 'std-22'],
    affinityDetails: [
      { targetStudentId: 'std-5', level: 'high', category: 'Trabalho em Equipe / Projetos' },
      { targetStudentId: 'std-14', level: 'medium', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-2', level: 'critical', category: 'Conversa Excessiva / Dispersão' },
      { targetStudentId: 'std-17', level: 'moderate', category: 'Conflito / Atrito Pessoal' },
      { targetStudentId: 'std-22', level: 'mild', category: 'Distração Mútua / Brincadeiras' },
    ],
  },
  {
    id: 'std-10',
    rollNumber: 10,
    name: 'Gabriela Duarte',
    nickname: 'Gabi',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'any',
    affinities: ['std-6', 'std-16'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-6', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-16', level: 'medium', category: 'Acolhimento & Adaptação' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-11',
    rollNumber: 11,
    name: 'Guilherme Toledo',
    nickname: 'Gui',
    gender: 'M',
    avatarColor: '#059669',
    behavior: 'calm',
    specialNeeds: ['hearing_impairment'],
    specialNeedsNotes: 'Deficiência auditiva leve no ouvido esquerdo. Melhor nas primeiras filas.',
    preferredRow: 'front',
    affinities: ['std-5', 'std-13'],
    antiAffinities: ['std-14'],
    affinityDetails: [
      { targetStudentId: 'std-5', level: 'high', category: 'Apoio Pedagógico / Monitoria' },
      { targetStudentId: 'std-13', level: 'medium', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-14', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
    ],
  },
  {
    id: 'std-12',
    rollNumber: 12,
    name: 'Helena Machado',
    nickname: 'Helô',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'moderate',
    specialNeeds: [],
    preferredRow: 'front',
    affinities: ['std-1', 'std-16'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-1', level: 'medium', category: 'Apoio Pedagógico / Monitoria' },
      { targetStudentId: 'std-16', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-13',
    rollNumber: 13,
    name: 'Henrique Barros',
    nickname: 'Rique',
    gender: 'M',
    avatarColor: '#047857',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-8', 'std-11'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-8', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-11', level: 'medium', category: 'Foco Compartilhado' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-14',
    rollNumber: 14,
    name: 'Igor Peixoto',
    nickname: 'Igor',
    gender: 'M',
    avatarColor: '#f97316',
    behavior: 'talkative',
    specialNeeds: [],
    preferredRow: 'back',
    affinities: ['std-9', 'std-21'],
    antiAffinities: ['std-2', 'std-4', 'std-5', 'std-11'],
    affinityDetails: [
      { targetStudentId: 'std-9', level: 'medium', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-21', level: 'high', category: 'Trabalho em Equipe / Projetos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-2', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
      { targetStudentId: 'std-4', level: 'critical', category: 'Conflito / Atrito Pessoal' },
      { targetStudentId: 'std-5', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
      { targetStudentId: 'std-11', level: 'mild', category: 'Distração Mútua / Brincadeiras' },
    ],
  },
  {
    id: 'std-15',
    rollNumber: 15,
    name: 'Isabela Fontes',
    nickname: 'Isa',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'moderate',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-7', 'std-19'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-7', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-19', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-16',
    rollNumber: 16,
    name: 'Juliana Pires',
    nickname: 'Ju',
    gender: 'F',
    avatarColor: '#059669',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'front',
    affinities: ['std-10', 'std-12'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-10', level: 'medium', category: 'Acolhimento & Adaptação' },
      { targetStudentId: 'std-12', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-17',
    rollNumber: 17,
    name: 'Leonardo Antunes',
    nickname: 'Léo',
    gender: 'M',
    avatarColor: '#047857',
    behavior: 'moderate',
    specialNeeds: ['tall_student'],
    preferredRow: 'back',
    affinities: ['std-8', 'std-20'],
    antiAffinities: ['std-9'],
    affinityDetails: [
      { targetStudentId: 'std-8', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-20', level: 'medium', category: 'Trabalho em Equipe / Projetos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-9', level: 'moderate', category: 'Conflito / Atrito Pessoal' },
    ],
  },
  {
    id: 'std-18',
    rollNumber: 18,
    name: 'Luana Rezende',
    nickname: 'Lu',
    gender: 'F',
    avatarColor: '#d97706',
    behavior: 'talkative',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-19', 'std-23'],
    antiAffinities: ['std-1', 'std-7'],
    affinityDetails: [
      { targetStudentId: 'std-19', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-23', level: 'medium', category: 'Acolhimento & Adaptação' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-1', level: 'moderate', category: 'Conversa Excessiva / Dispersão' },
      { targetStudentId: 'std-7', level: 'critical', category: 'Conflito / Atrito Pessoal' },
    ],
  },
  {
    id: 'std-19',
    rollNumber: 19,
    name: 'Manuela Nogueira',
    nickname: 'Manu',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'moderate',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-15', 'std-18'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-15', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-18', level: 'medium', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-20',
    rollNumber: 20,
    name: 'Mateus Aragão',
    nickname: 'Mat',
    gender: 'M',
    avatarColor: '#059669',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'any',
    affinities: ['std-17', 'std-24'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-17', level: 'medium', category: 'Trabalho em Equipe / Projetos' },
      { targetStudentId: 'std-24', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-21',
    rollNumber: 21,
    name: 'Nicolas Viana',
    nickname: 'Nick',
    gender: 'M',
    avatarColor: '#f97316',
    behavior: 'talkative',
    specialNeeds: [],
    preferredRow: 'middle',
    affinities: ['std-14', 'std-22'],
    antiAffinities: ['std-5'],
    affinityDetails: [
      { targetStudentId: 'std-14', level: 'high', category: 'Trabalho em Equipe / Projetos' },
      { targetStudentId: 'std-22', level: 'medium', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-5', level: 'critical', category: 'Conversa Excessiva / Dispersão' },
    ],
  },
  {
    id: 'std-22',
    rollNumber: 22,
    name: 'Otávio Martins',
    nickname: 'Oto',
    gender: 'M',
    avatarColor: '#047857',
    behavior: 'moderate',
    specialNeeds: [],
    preferredRow: 'back',
    affinities: ['std-21'],
    antiAffinities: ['std-9'],
    affinityDetails: [
      { targetStudentId: 'std-21', level: 'medium', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [
      { targetStudentId: 'std-9', level: 'mild', category: 'Distração Mútua / Brincadeiras' },
    ],
  },
  {
    id: 'std-23',
    rollNumber: 23,
    name: 'Rafaela Campos',
    nickname: 'Rafa',
    gender: 'F',
    avatarColor: '#10b981',
    behavior: 'calm',
    specialNeeds: ['low_vision'],
    specialNeedsNotes: 'Miopia severa. Prefere as primeiras fileiras centrais.',
    preferredRow: 'front',
    affinities: ['std-18', 'std-24'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-18', level: 'medium', category: 'Acolhimento & Adaptação' },
      { targetStudentId: 'std-24', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
  {
    id: 'std-24',
    rollNumber: 24,
    name: 'Sofia Alencar',
    nickname: 'Sofi',
    gender: 'F',
    avatarColor: '#059669',
    behavior: 'calm',
    specialNeeds: [],
    preferredRow: 'front',
    affinities: ['std-20', 'std-23'],
    antiAffinities: [],
    affinityDetails: [
      { targetStudentId: 'std-20', level: 'high', category: 'Amizade Produtiva / Estudos' },
      { targetStudentId: 'std-23', level: 'high', category: 'Amizade Produtiva / Estudos' },
    ],
    antiAffinityDetails: [],
  },
];

export const INITIAL_INSTITUTIONS: Institution[] = [
  {
    id: 'inst-fleming-prime',
    name: 'Fleming Prime Medicina - Matriz',
    code: 'FLEMING-PRIME',
    cnpj: '12.345.678/0001-90',
    status: 'active',
    contactEmail: 'contato@flemingmedicina.com.br',
    contactPhone: '(82) 3333-1000',
    city: 'Maceió',
    state: 'AL',
    notes: 'Unidade central e preparatório de alta performance para vestibulares de Medicina.',
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now(),
  },
  {
    id: 'inst-fleming-colegio',
    name: 'Colégio Fleming - Unidade Farol',
    code: 'FLEMING-FAROL',
    cnpj: '12.345.678/0002-71',
    status: 'active',
    contactEmail: 'direcao.farol@flemingeducacao.com.br',
    contactPhone: '(82) 3333-2000',
    city: 'Maceió',
    state: 'AL',
    notes: 'Ensino Fundamental II e Ensino Médio com foco em formação integral.',
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now(),
  },
  {
    id: 'inst-colegio-modelo',
    name: 'Instituto Educacional Horizon',
    code: 'HORIZON-SUL',
    cnpj: '98.765.432/0001-10',
    status: 'active',
    contactEmail: 'gestao@horizoneducacao.com.br',
    contactPhone: '(11) 4004-9000',
    city: 'São Paulo',
    state: 'SP',
    notes: 'Escola parceira conveniada para metodologia de espelhos de classe.',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
  },
];

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'user-master-1',
    name: 'Administrador Master Fleming',
    email: 'master@flemingeducacao.com.br',
    password: 'master@fleming2026',
    role: 'master',
    isActive: true,
    avatarColor: '#10b981',
    phone: '(82) 99999-0001',
    createdAt: Date.now() - 86400000 * 40,
    lastLoginAt: Date.now(),
  },
  {
    id: 'user-gestor-prime',
    name: 'Cláudia Valença (Gestora)',
    email: 'claudia.gestora@flemingmedicina.com.br',
    password: 'gestor@prime2026',
    role: 'manager',
    institutionId: 'inst-fleming-prime',
    isActive: true,
    avatarColor: '#059669',
    phone: '(82) 98888-1002',
    createdAt: Date.now() - 86400000 * 25,
    lastLoginAt: Date.now() - 3600000 * 2,
  },
  {
    id: 'user-gestor-farol',
    name: 'Marcos Andrade (Gestor Farol)',
    email: 'marcos.gestor@flemingeducacao.com.br',
    password: 'gestor@farol2026',
    role: 'manager',
    institutionId: 'inst-fleming-colegio',
    isActive: true,
    avatarColor: '#0d9488',
    phone: '(82) 97777-2003',
    createdAt: Date.now() - 86400000 * 15,
    lastLoginAt: Date.now() - 3600000 * 12,
  },
  {
    id: 'user-gestor-horizon',
    name: 'Juliana Paes (Gestora Horizon)',
    email: 'juliana@horizoneducacao.com.br',
    password: 'gestor@horizon2026',
    role: 'manager',
    institutionId: 'inst-colegio-modelo',
    isActive: true,
    avatarColor: '#6366f1',
    phone: '(11) 96666-3004',
    createdAt: Date.now() - 86400000 * 8,
    lastLoginAt: Date.now() - 86400000,
  },
];

export const INITIAL_CLASSROOMS: Classroom[] = [
  {
    id: 'class-fleming-med',
    institutionId: 'inst-fleming-prime',
    name: 'Extensivo Medicina - Turma Alfa',
    grade: 'Pré-Vestibular / Medicina',
    schoolName: 'Fleming Prime Medicina - Matriz',
    teacherName: 'Profª Cláudia Valença',
    academicYear: '2026',
    roomNumber: 'Sala 104 - Fleming Prime',
    roomConfig: createDefaultRoomConfig(5, 6, 'rows'),
    students: SAMPLE_STUDENTS_7B,
    seatingMap: {},
    lockedDesks: {},
    customAffinityCategories: ['Apoio em Redação Nota 1000', 'Dupla de Biologia/Química'],
    customAntiAffinityCategories: ['Dispersão em Simulado', 'Conversa em Resolução de Prova'],
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'class-fleming-3em',
    institutionId: 'inst-fleming-colegio',
    name: '3º Ano EM - Sala Fleming 204',
    grade: 'Ensino Médio',
    schoolName: 'Colégio Fleming - Unidade Farol',
    teacherName: 'Prof. Marcos Andrade',
    academicYear: '2026',
    roomNumber: 'Sala 204',
    roomConfig: createDefaultRoomConfig(5, 6, 'pairs'),
    students: SAMPLE_STUDENTS_7B.slice(0, 18),
    seatingMap: {},
    lockedDesks: {},
    customAffinityCategories: ['Monitoria de Matemática'],
    customAntiAffinityCategories: [],
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now(),
  },
  {
    id: 'class-horizon-1a',
    institutionId: 'inst-colegio-modelo',
    name: '1º Ano EM - Turma Aurora',
    grade: 'Ensino Médio Integral',
    schoolName: 'Instituto Educacional Horizon',
    teacherName: 'Profª Renata Bastos',
    academicYear: '2026',
    roomNumber: 'Laboratório 3',
    roomConfig: createDefaultRoomConfig(5, 6, 'rows'),
    students: SAMPLE_STUDENTS_7B.slice(0, 14),
    seatingMap: {},
    lockedDesks: {},
    customAffinityCategories: ['Grupo de Iniciação Científica'],
    customAntiAffinityCategories: [],
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now(),
  }
];
